version: '3.7'

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: pettix
    container_name: app_dev
    command: rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - mongo
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    ports:
      - '27017:27017'